version: '3.9'
services:
  # phpコンテナ
  php:
    build: ./infra/php
    volumes:
      - ./app/backend:/data
  # nginxコンテナ
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./app/backend:/data
      - ./app/frontend:/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  # mysqlコンテナ
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
  #redisコンテナ
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379
  #next.jsコンテナ
  next:
    build: ./infra/next
    tty: true
    volumes:
      - ./app/frontend:/app
    #command: sh -c "npm run dev"
volumes:
  db-store:
  redis-volume: